AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creation of an ECR repo for AWSClusterManagersDemo example

Resources:
  ECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "awsclustermanagers-demo"

Outputs:
  AWSClusterManagersDemoRepoUri:
    Description: Name of the ECR Repository used in the AWSClusterManagersDemo example
    Value: !GetAtt ECRRepo.RepositoryUri
    Export:
      Name: AWSClusterManagersDemoRepoUri
